title:    Ivan Umpire # your name (or website title) here
logo: "/images/fotoivan.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Lima, Perú
  <br><br>
  Experiencia en Data Science aplicado a Negocios.
  <br><br>
  Experience in Data Science for Business
  <br><br>
  <a href="https://www.linkedin.com/in/ivan-umpire-696a6826/">Perfil de LinkedIn / Profile</a> 
  <br><br>
  <a href="/pdf/plantilla-curriculum-blanco.pdf">Curriculum Vitae / Resume </a> 
  
theme: jekyll-theme-minimal
